/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;

/**
 *
 * @author luisa
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setUndecorated(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtpass = new javax.swing.JPasswordField();
        lcerrar = new javax.swing.JLabel();
        lingresar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGIN.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(180, 180));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 240));
        jLabel1.getAccessibleContext().setAccessibleName("");

        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Ingrese su nombre de usuario");
        txtuser.setBorder(null);
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtuserFocusLost(evt);
            }
        });
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtuserMouseClicked(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
        });
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 290, 30));

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel3.setText("INICIAR SESIÓN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 190, 30));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setText("CONTRASEÑA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 290, 10));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setText("USUARIO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 290, 10));

        txtpass.setForeground(new java.awt.Color(204, 204, 204));
        txtpass.setText("********");
        txtpass.setBorder(null);
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpassMouseClicked(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassKeyReleased(evt);
            }
        });
        jPanel1.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 290, 30));

        lcerrar.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lcerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcerrar.setText("X");
        lcerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lcerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lcerrar.setName(""); // NOI18N
        lcerrar.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                lcerrarMouseWheelMoved(evt);
            }
        });
        lcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lcerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lcerrarMouseExited(evt);
            }
        });
        jPanel1.add(lcerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        lingresar.setBackground(new java.awt.Color(255, 255, 255));
        lingresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lingresar.setText("INGRESAR");
        lingresar.setToolTipText("");
        lingresar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lingresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lingresarMouseClicked(evt);
            }
        });
        jPanel1.add(lingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setBounds(0, 0, 668, 389);
    }// </editor-fold>//GEN-END:initComponents

    private void lcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lcerrarMouseClicked

    private void lingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lingresarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lingresarMouseClicked

    private void txtuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusLost
        if(txtuser.getText().equals("")){
            txtuser.setText("Ingrese su nombre de usuario");
            txtuser.setForeground(Color.gray);
            
        }
    }//GEN-LAST:event_txtuserFocusLost

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        if (txtuser.getText().equals("Ingrese su nombre de usuario")) {
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getPassword()).isEmpty()) {
            txtpass.setText("********");
            txtpass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserKeyPressed

    private void txtuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMouseClicked
        if (txtuser.getText().equals("Ingrese su nombre de usuario")) {
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getPassword()).isEmpty()) {
            txtpass.setText("********");
            txtpass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserMouseClicked

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed
        if (String.valueOf(txtpass.getPassword()).equals("********")) {
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if (txtuser.getText().isEmpty()) {
            txtuser.setText("Ingrese su nombre de usuario");
            txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpassKeyPressed

    private void txtpassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyReleased

    }//GEN-LAST:event_txtpassKeyReleased

    private void txtpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMouseClicked
        if (String.valueOf(txtpass.getPassword()).equals("********")) {
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if (txtuser.getText().isEmpty()) {
            txtuser.setText("Ingrese su nombre de usuario");
            txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpassMouseClicked

    private void lcerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcerrarMouseEntered
        lcerrar.setBackground(Color.red);
        lcerrar.setForeground(Color.white);
    }//GEN-LAST:event_lcerrarMouseEntered

    private void lcerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcerrarMouseExited
        
    }//GEN-LAST:event_lcerrarMouseExited

    private void lcerrarMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_lcerrarMouseWheelMoved

    }//GEN-LAST:event_lcerrarMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lcerrar;
    private javax.swing.JLabel lingresar;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
