
package view;

import java.awt.BorderLayout;
import java.awt.Color;

public class Menu extends javax.swing.JPanel {
    Color blue  =  new Color(0,171,228);
    Color bluelight = new Color(233,241,250);
    Color blueMedio = new Color(200,241,250);
    
    
    

    public Menu() {
        initComponents();
        lgestion.setBackground(blue);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lconfiguracion = new javax.swing.JLabel();
        lgestion = new javax.swing.JLabel();
        lmantenimiento = new javax.swing.JLabel();
        lcompras = new javax.swing.JLabel();
        ltesoreria = new javax.swing.JLabel();
        lreportes = new javax.swing.JLabel();
        lherramientas = new javax.swing.JLabel();
        lalmacen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1390, 30));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(233, 241, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(1390, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lconfiguracion.setBackground(new java.awt.Color(233, 241, 250));
        lconfiguracion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lconfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lconfiguracion.setText("Configuración");
        lconfiguracion.setNextFocusableComponent(jPanel1);
        lconfiguracion.setOpaque(true);
        lconfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lconfiguracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lconfiguracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lconfiguracionMouseExited(evt);
            }
        });
        jPanel1.add(lconfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 100, 30));

        lgestion.setBackground(new java.awt.Color(233, 241, 250));
        lgestion.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lgestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lgestion.setText("Gestión");
        lgestion.setOpaque(true);
        lgestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lgestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lgestionMouseExited(evt);
            }
        });
        jPanel1.add(lgestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        lmantenimiento.setBackground(new java.awt.Color(233, 241, 250));
        lmantenimiento.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lmantenimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lmantenimiento.setText("Mantenimiento");
        lmantenimiento.setOpaque(true);
        lmantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lmantenimientoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lmantenimientoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lmantenimientoMouseExited(evt);
            }
        });
        jPanel1.add(lmantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 110, 30));

        lcompras.setBackground(new java.awt.Color(233, 241, 250));
        lcompras.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lcompras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lcompras.setText("Compras");
        lcompras.setOpaque(true);
        lcompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcomprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lcomprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lcomprasMouseExited(evt);
            }
        });
        jPanel1.add(lcompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 80, 30));

        ltesoreria.setBackground(new java.awt.Color(233, 241, 250));
        ltesoreria.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        ltesoreria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ltesoreria.setText("Tesoreria");
        ltesoreria.setOpaque(true);
        ltesoreria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ltesoreriaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ltesoreriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ltesoreriaMouseExited(evt);
            }
        });
        jPanel1.add(ltesoreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 80, 30));

        lreportes.setBackground(new java.awt.Color(233, 241, 250));
        lreportes.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lreportes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lreportes.setText("Reportes");
        lreportes.setOpaque(true);
        lreportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lreportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lreportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lreportesMouseExited(evt);
            }
        });
        jPanel1.add(lreportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 80, 30));

        lherramientas.setBackground(new java.awt.Color(233, 241, 250));
        lherramientas.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lherramientas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lherramientas.setText("Herramientas");
        lherramientas.setOpaque(true);
        lherramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lherramientasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lherramientasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lherramientasMouseExited(evt);
            }
        });
        jPanel1.add(lherramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 100, 30));

        lalmacen.setBackground(new java.awt.Color(233, 241, 250));
        lalmacen.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lalmacen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lalmacen.setText("Almacen");
        lalmacen.setOpaque(true);
        lalmacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lalmacenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lalmacenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lalmacenMouseExited(evt);
            }
        });
        jPanel1.add(lalmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 80, 30));

        add(jPanel1);

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void lgestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgestionMouseEntered
        if(lgestion.getBackground().equals(blue)){
            lgestion.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lgestion.setBackground(blueMedio);
        }
    }//GEN-LAST:event_lgestionMouseEntered

    private void lgestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgestionMouseExited
        if(lgestion.getBackground().equals(blue)){
            lgestion.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lgestion.setBackground(bluelight);
        }
        
        
    }//GEN-LAST:event_lgestionMouseExited

    private void lgestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgestionMouseClicked
        MenuGestion gestion = new MenuGestion();
        MenuPrincipal.panelMenu.removeAll();
        MenuPrincipal.panelMenu.add(gestion, BorderLayout.CENTER);
        MenuPrincipal.panelMenu.revalidate();
        MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(bluelight);
        lgestion.setBackground(blue);
        ltesoreria.setBackground(bluelight);
        lalmacen.setBackground(bluelight);
        lcompras.setBackground(bluelight);
        lconfiguracion.setBackground(bluelight);
        lreportes.setBackground(bluelight);
        lherramientas.setBackground(bluelight);
        
        
    }//GEN-LAST:event_lgestionMouseClicked

    private void lmantenimientoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmantenimientoMouseEntered
        if(lmantenimiento.getBackground().equals(blue)){
            lmantenimiento.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lmantenimiento.setBackground(blueMedio);
        }
    }//GEN-LAST:event_lmantenimientoMouseEntered

    private void lmantenimientoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmantenimientoMouseExited
        if(lmantenimiento.getBackground().equals(blue)){
            lmantenimiento.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lmantenimiento.setBackground(bluelight);
        }
        
    }//GEN-LAST:event_lmantenimientoMouseExited

    private void lmantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmantenimientoMouseClicked
        MenuMantenimiento mantenimiento = new MenuMantenimiento();
        MenuPrincipal.panelMenu.removeAll();
        MenuPrincipal.panelMenu.add(mantenimiento, BorderLayout.CENTER);
        MenuPrincipal.panelMenu.revalidate();
        MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(blue);
        lgestion.setBackground(bluelight);
        ltesoreria.setBackground(bluelight);
        lalmacen.setBackground(bluelight);
        lcompras.setBackground(bluelight);
        lconfiguracion.setBackground(bluelight);
        lreportes.setBackground(bluelight);
        lherramientas.setBackground(bluelight);
        
    }//GEN-LAST:event_lmantenimientoMouseClicked

    private void lcomprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcomprasMouseClicked
        //MenuMantenimiento mantenimiento = new MenuMantenimiento();
        //MenuPrincipal.panelMenu.removeAll();
        //MenuPrincipal.panelMenu.add(mantenimiento, BorderLayout.CENTER);
        //MenuPrincipal.panelMenu.revalidate();
        //MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(bluelight);
        lgestion.setBackground(bluelight);
        ltesoreria.setBackground(bluelight);
        lalmacen.setBackground(bluelight);
        lcompras.setBackground(blue);
        lconfiguracion.setBackground(bluelight);
        lreportes.setBackground(bluelight);
        lherramientas.setBackground(bluelight);
    }//GEN-LAST:event_lcomprasMouseClicked

    private void lcomprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcomprasMouseEntered
        if(lcompras.getBackground().equals(blue)){
            lcompras.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lcompras.setBackground(blueMedio);
        }
    }//GEN-LAST:event_lcomprasMouseEntered

    private void lcomprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcomprasMouseExited
        if(lcompras.getBackground().equals(blue)){
            lcompras.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lcompras.setBackground(bluelight);
        }
    }//GEN-LAST:event_lcomprasMouseExited

    private void ltesoreriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltesoreriaMouseClicked
        //MenuMantenimiento mantenimiento = new MenuMantenimiento();
        //MenuPrincipal.panelMenu.removeAll();
        //MenuPrincipal.panelMenu.add(mantenimiento, BorderLayout.CENTER);
        //MenuPrincipal.panelMenu.revalidate();
        //MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(bluelight);
        lgestion.setBackground(bluelight);
        ltesoreria.setBackground(blue);
        lalmacen.setBackground(bluelight);
        lcompras.setBackground(bluelight);
        lconfiguracion.setBackground(bluelight);
        lreportes.setBackground(bluelight);
        lherramientas.setBackground(bluelight);
    }//GEN-LAST:event_ltesoreriaMouseClicked

    private void ltesoreriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltesoreriaMouseEntered
        if(ltesoreria.getBackground().equals(blue)){
            ltesoreria.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            ltesoreria.setBackground(blueMedio);
        }
    }//GEN-LAST:event_ltesoreriaMouseEntered

    private void ltesoreriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ltesoreriaMouseExited
        if(ltesoreria.getBackground().equals(blue)){
            ltesoreria.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            ltesoreria.setBackground(bluelight);
        }
    }//GEN-LAST:event_ltesoreriaMouseExited

    private void lreportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lreportesMouseClicked
        //MenuMantenimiento mantenimiento = new MenuMantenimiento();
        //MenuPrincipal.panelMenu.removeAll();
        //MenuPrincipal.panelMenu.add(mantenimiento, BorderLayout.CENTER);
        //MenuPrincipal.panelMenu.revalidate();
        //MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(bluelight);
        lgestion.setBackground(bluelight);
        ltesoreria.setBackground(bluelight);
        lalmacen.setBackground(bluelight);
        lcompras.setBackground(bluelight);
        lconfiguracion.setBackground(bluelight);
        lreportes.setBackground(blue);
        lherramientas.setBackground(bluelight);
    }//GEN-LAST:event_lreportesMouseClicked

    private void lreportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lreportesMouseEntered
        if(lreportes.getBackground().equals(blue)){
            lreportes.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lreportes.setBackground(blueMedio);
        }
    }//GEN-LAST:event_lreportesMouseEntered

    private void lreportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lreportesMouseExited
        if(lreportes.getBackground().equals(blue)){
            lreportes.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lreportes.setBackground(bluelight);
        }
    }//GEN-LAST:event_lreportesMouseExited

    private void lalmacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lalmacenMouseClicked
        //MenuMantenimiento mantenimiento = new MenuMantenimiento();
        //MenuPrincipal.panelMenu.removeAll();
        //MenuPrincipal.panelMenu.add(mantenimiento, BorderLayout.CENTER);
        //MenuPrincipal.panelMenu.revalidate();
        //MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(bluelight);
        lgestion.setBackground(bluelight);
        ltesoreria.setBackground(bluelight);
        lalmacen.setBackground(blue);
        lcompras.setBackground(bluelight);
        lconfiguracion.setBackground(bluelight);
        lreportes.setBackground(bluelight);
        lherramientas.setBackground(bluelight);
    }//GEN-LAST:event_lalmacenMouseClicked

    private void lalmacenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lalmacenMouseEntered
        if(lalmacen.getBackground().equals(blue)){
            lalmacen.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lalmacen.setBackground(blueMedio);
        }
    }//GEN-LAST:event_lalmacenMouseEntered

    private void lalmacenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lalmacenMouseExited
        if(lalmacen.getBackground().equals(blue)){
            lalmacen.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lalmacen.setBackground(bluelight);
        }
    }//GEN-LAST:event_lalmacenMouseExited

    private void lherramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lherramientasMouseClicked
        //MenuMantenimiento mantenimiento = new MenuMantenimiento();
        //MenuPrincipal.panelMenu.removeAll();
        //MenuPrincipal.panelMenu.add(mantenimiento, BorderLayout.CENTER);
        //MenuPrincipal.panelMenu.revalidate();
        //MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(bluelight);
        lgestion.setBackground(bluelight);
        ltesoreria.setBackground(bluelight);
        lalmacen.setBackground(bluelight);
        lcompras.setBackground(bluelight);
        lconfiguracion.setBackground(bluelight);
        lreportes.setBackground(bluelight);
        lherramientas.setBackground(blue);
    }//GEN-LAST:event_lherramientasMouseClicked

    private void lherramientasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lherramientasMouseEntered
       if(lherramientas.getBackground().equals(blue)){
            lherramientas.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lherramientas.setBackground(blueMedio);
        }
    }//GEN-LAST:event_lherramientasMouseEntered

    private void lherramientasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lherramientasMouseExited
        if(lherramientas.getBackground().equals(blue)){
            lherramientas.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lherramientas.setBackground(bluelight);
        }
    }//GEN-LAST:event_lherramientasMouseExited

    private void lconfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lconfiguracionMouseClicked
        //MenuMantenimiento mantenimiento = new MenuMantenimiento();
        //MenuPrincipal.panelMenu.removeAll();
        //MenuPrincipal.panelMenu.add(mantenimiento, BorderLayout.CENTER);
        //MenuPrincipal.panelMenu.revalidate();
        //MenuPrincipal.panelMenu.repaint();
        lmantenimiento.setBackground(bluelight);
        lgestion.setBackground(bluelight);
        ltesoreria.setBackground(bluelight);
        lalmacen.setBackground(bluelight);
        lcompras.setBackground(bluelight);
        lconfiguracion.setBackground(blue);
        lreportes.setBackground(bluelight);
        lherramientas.setBackground(bluelight);
    }//GEN-LAST:event_lconfiguracionMouseClicked

    private void lconfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lconfiguracionMouseEntered
        if(lconfiguracion.getBackground().equals(blue)){
            lconfiguracion.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lconfiguracion.setBackground(blueMedio);
        }
    }//GEN-LAST:event_lconfiguracionMouseEntered

    private void lconfiguracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lconfiguracionMouseExited
        if(lconfiguracion.getBackground().equals(blue)){
            lconfiguracion.setBackground(blue);
            //lgestion.setBackground(new Color(135,206,235));
        }else{
            lconfiguracion.setBackground(bluelight);
        }
    }//GEN-LAST:event_lconfiguracionMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lalmacen;
    private javax.swing.JLabel lcompras;
    private javax.swing.JLabel lconfiguracion;
    private javax.swing.JLabel lgestion;
    private javax.swing.JLabel lherramientas;
    private javax.swing.JLabel lmantenimiento;
    private javax.swing.JLabel lreportes;
    private javax.swing.JLabel ltesoreria;
    // End of variables declaration//GEN-END:variables
}
